export const authTypes = {
  REGESTIR_SUCCESS: "REGESTIR_SUCCESS",
  REGESTIR_FAIL: "REGESTIR_FAIL",
  USER_LOADED: "USER_LOADED",
  AUTH_ERROR: "AUTH_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  UPDATE_AVATAR: "UPDATE_AVATAR",
};
