export const profile = {
  PROFILE_SUCCESS: "PROFILE_SUCCESS",
  PROFILE_FAIL: "PROFILE_FAIL",
  CLEAR_PROFILE: "CLEAR_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  GET_PROFILES: "GET_PROFILES",
  GET_PROFILES_FAIL: "GET_PROFILES_FAIL",
  GET_PROFILE_ID: "GET_PROFILE_ID",
  DELETE_PROFILE: "DELETE_PROFILE",
  GET_REPOS: "GET_REPOS",
  GET_REPOS_FAIL: "GET_REPOS_FAIL",
  PROFILE_SHOW_SUCCESS: "PROFILE_SHOW_SUCCESS",
};
